///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Click2Win
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Click2WinRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("cd2c57e3-b756-42f6-a549-edb385d4d5eb")]
    public partial class Click2WinRepository : RepoGenBaseFolder
    {
        static Click2WinRepository instance = new Click2WinRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Click2WinRepository element repository.
        /// </summary>
        [RepositoryFolder("cd2c57e3-b756-42f6-a549-edb385d4d5eb")]
        public static Click2WinRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Click2WinRepository() 
            : base("Click2WinRepository", "/", null, 0, false, "cd2c57e3-b756-42f6-a549-edb385d4d5eb", ".\\RepositoryImages\\Click2WinRepositorycd2c57e3.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("cd2c57e3-b756-42f6-a549-edb385d4d5eb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class Click2WinRepositoryFolders
    {
    }
#pragma warning restore 0436
}