///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_Element_Search
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_Element_SearchRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("b87b1a35-2af1-43bf-91e0-a96bdda485fe")]
    public partial class Test_Element_SearchRepository : RepoGenBaseFolder
    {
        static Test_Element_SearchRepository instance = new Test_Element_SearchRepository();

        /// <summary>
        /// Gets the singleton class instance representing the Test_Element_SearchRepository element repository.
        /// </summary>
        [RepositoryFolder("b87b1a35-2af1-43bf-91e0-a96bdda485fe")]
        public static Test_Element_SearchRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_Element_SearchRepository() 
            : base("Test_Element_SearchRepository", "/", null, 0, false, "b87b1a35-2af1-43bf-91e0-a96bdda485fe", ".\\RepositoryImages\\Test_Element_SearchRepositoryb87b1a35.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b87b1a35-2af1-43bf-91e0-a96bdda485fe")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class Test_Element_SearchRepositoryFolders
    {
    }
#pragma warning restore 0436
}