///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestCase1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestCase1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("d04a2cf3-3081-4130-8405-309329f54da0")]
    public partial class TestCase1Repository : RepoGenBaseFolder
    {
        static TestCase1Repository instance = new TestCase1Repository();
        TestCase1RepositoryFolders.AccessUHUniversityOfHoustonAppFolder _accessuhuniversityofhouston;
        TestCase1RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder _accessuhuniversityofhoustongoogl;

        /// <summary>
        /// Gets the singleton class instance representing the TestCase1Repository element repository.
        /// </summary>
        [RepositoryFolder("d04a2cf3-3081-4130-8405-309329f54da0")]
        public static TestCase1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestCase1Repository() 
            : base("TestCase1Repository", "/", null, 0, false, "d04a2cf3-3081-4130-8405-309329f54da0", ".\\RepositoryImages\\TestCase1Repositoryd04a2cf3.rximgres")
        {
            _accessuhuniversityofhouston = new TestCase1RepositoryFolders.AccessUHUniversityOfHoustonAppFolder(this);
            _accessuhuniversityofhoustongoogl = new TestCase1RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d04a2cf3-3081-4130-8405-309329f54da0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AccessUHUniversityOfHouston folder.
        /// </summary>
        [RepositoryFolder("015b6236-4e4f-4b93-9782-08ae98336df7")]
        public virtual TestCase1RepositoryFolders.AccessUHUniversityOfHoustonAppFolder AccessUHUniversityOfHouston
        {
            get { return _accessuhuniversityofhouston; }
        }

        /// <summary>
        /// The AccessUHUniversityOfHoustonGoogl folder.
        /// </summary>
        [RepositoryFolder("5e875f3f-4c91-49e1-acd1-a2fda019d428")]
        public virtual TestCase1RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder AccessUHUniversityOfHoustonGoogl
        {
            get { return _accessuhuniversityofhoustongoogl; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class TestCase1RepositoryFolders
    {
        /// <summary>
        /// The AccessUHUniversityOfHoustonAppFolder folder.
        /// </summary>
        [RepositoryFolder("015b6236-4e4f-4b93-9782-08ae98336df7")]
        public partial class AccessUHUniversityOfHoustonAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpsaccessuhuheduimgiconslearn9Info;

            /// <summary>
            /// Creates a new AccessUHUniversityOfHouston  folder.
            /// </summary>
            public AccessUHUniversityOfHoustonAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AccessUHUniversityOfHouston", "/dom[@domain='accessuh.uh.edu']", parentFolder, 30000, null, false, "015b6236-4e4f-4b93-9782-08ae98336df7", "")
            {
                _httpsaccessuhuheduimgiconslearn9Info = new RepoItemInfo(this, "HttpsAccessuhUhEduImgIconsLearn9", ".//div[#'portal_area']/?/?/a[@innertext='Blackboard Learn 9']/?/?/img[@src='https://accessuh.uh.edu/img/icons/learn9.png']", 30000, null, "009b6ef5-c03d-43fc-9e42-2768e7553843");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("015b6236-4e4f-4b93-9782-08ae98336df7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("015b6236-4e4f-4b93-9782-08ae98336df7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpsAccessuhUhEduImgIconsLearn9 item.
            /// </summary>
            [RepositoryItem("009b6ef5-c03d-43fc-9e42-2768e7553843")]
            public virtual Ranorex.ImgTag HttpsAccessuhUhEduImgIconsLearn9
            {
                get
                {
                    return _httpsaccessuhuheduimgiconslearn9Info.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpsAccessuhUhEduImgIconsLearn9 item info.
            /// </summary>
            [RepositoryItemInfo("009b6ef5-c03d-43fc-9e42-2768e7553843")]
            public virtual RepoItemInfo HttpsAccessuhUhEduImgIconsLearn9Info
            {
                get
                {
                    return _httpsaccessuhuheduimgiconslearn9Info;
                }
            }
        }

        /// <summary>
        /// The AccessUHUniversityOfHoustonGooglAppFolder folder.
        /// </summary>
        [RepositoryFolder("5e875f3f-4c91-49e1-acd1-a2fda019d428")]
        public partial class AccessUHUniversityOfHoustonGooglAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element1250396752Info;
            RepoItemInfo _element1250361936Info;

            /// <summary>
            /// Creates a new AccessUHUniversityOfHoustonGoogl  folder.
            /// </summary>
            public AccessUHUniversityOfHoustonGooglAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AccessUHUniversityOfHoustonGoogl", "/form[@title~'^AccessUH\\ -\\ University\\ of\\ ']", parentFolder, 30000, null, true, "5e875f3f-4c91-49e1-acd1-a2fda019d428", "")
            {
                _element1250396752Info = new RepoItemInfo(this, "Element1250396752", "element[@controlid='-1250396752']", 30000, null, "e7b50c71-08bd-4173-9331-d95280909fba");
                _element1250361936Info = new RepoItemInfo(this, "Element1250361936", "element[@controlid='-1250361936']", 30000, null, "55f3cb99-1930-4ce6-892d-d0c85eb198d7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e875f3f-4c91-49e1-acd1-a2fda019d428")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e875f3f-4c91-49e1-acd1-a2fda019d428")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element1250396752 item.
            /// </summary>
            [RepositoryItem("e7b50c71-08bd-4173-9331-d95280909fba")]
            public virtual Ranorex.Unknown Element1250396752
            {
                get
                {
                    return _element1250396752Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1250396752 item info.
            /// </summary>
            [RepositoryItemInfo("e7b50c71-08bd-4173-9331-d95280909fba")]
            public virtual RepoItemInfo Element1250396752Info
            {
                get
                {
                    return _element1250396752Info;
                }
            }

            /// <summary>
            /// The Element1250361936 item.
            /// </summary>
            [RepositoryItem("55f3cb99-1930-4ce6-892d-d0c85eb198d7")]
            public virtual Ranorex.Unknown Element1250361936
            {
                get
                {
                    return _element1250361936Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1250361936 item info.
            /// </summary>
            [RepositoryItemInfo("55f3cb99-1930-4ce6-892d-d0c85eb198d7")]
            public virtual RepoItemInfo Element1250361936Info
            {
                get
                {
                    return _element1250361936Info;
                }
            }
        }

    }
#pragma warning restore 0436
}