'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Drawing
Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Repository
Imports Ranorex.Core.Testing

Namespace HeavyBid1._
    ''' <summary>
    ''' The class representing the HeavyBid1_0Repository element repository.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1"), _
    RepositoryFolder("68e4a2db-32ab-49b8-8f9b-f3646a746ab5")> _
    Partial Public Class HeavyBid1_0Repository
        Inherits RepoGenBaseFolder

        Shared _instance As HeavyBid1_0Repository = New HeavyBid1_0Repository()
        Dim _accessuhuniversityofhoustongoogl As HeavyBid1_0RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder

        ''' <summary>
        ''' Repository class constructor.
        ''' </summary>
        Public Sub New()
            MyBase.New("HeavyBid1_0Repository", "/", Nothing, 0, False,"68e4a2db-32ab-49b8-8f9b-f3646a746ab5", ".\RepositoryImages\HeavyBid1_0Repository68e4a2db.rximgres")
            _accessuhuniversityofhoustongoogl = New HeavyBid1_0RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder(Me)
        End Sub

        ''' <summary>
        ''' Gets the singleton class instance representing the HeavyBid1_0Repository element repository.
        ''' </summary>
        <RepositoryFolder("68e4a2db-32ab-49b8-8f9b-f3646a746ab5")> _
        Public Shared ReadOnly Property Instance() As HeavyBid1_0Repository
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"
#End Region

        ''' <summary>
        ''' The Self item info.
        ''' </summary>
        <RepositoryItemInfo("68e4a2db-32ab-49b8-8f9b-f3646a746ab5")> _
        Public Overridable ReadOnly Property SelfInfo() As RepoItemInfo
            Get
                Return _selfInfo
            End Get
        End Property

        ''' <summary>
        ''' The AccessUHUniversityOfHoustonGoogl folder.
        ''' </summary>
        <RepositoryFolder("e6f4104c-6f06-488c-ac35-02fa1ee32a38")> _
        Public Overridable ReadOnly Property AccessUHUniversityOfHoustonGoogl As HeavyBid1_0RepositoryFolders.AccessUHUniversityOfHoustonGooglAppFolder
            Get
                Return _accessuhuniversityofhoustongoogl
            End Get
        End Property
    End Class

    ''' <summary>
    ''' Inner folder classes.
    ''' </summary>
    <System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")> _
    Partial Public Class HeavyBid1_0RepositoryFolders

        ''' <summary>
        ''' The AccessUHUniversityOfHoustonGooglAppFolder folder.
        ''' </summary>
        <RepositoryFolder("e6f4104c-6f06-488c-ac35-02fa1ee32a38")> _
        Partial Public Class AccessUHUniversityOfHoustonGooglAppFolder
            Inherits RepoGenBaseFolder

            Dim _element1261217568Info As RepoItemInfo

            ''' <summary>
            ''' Creates a new AccessUHUniversityOfHoustonGoogl  folder.
            ''' </summary>
            Public Sub New(parentFolder As RepoGenBaseFolder)
                MyBase.New("AccessUHUniversityOfHoustonGoogl", "/form[@title~'^AccessUH\ -\ University\ of\ ']", parentFolder, 30000, Nothing, True, "e6f4104c-6f06-488c-ac35-02fa1ee32a38", ".\RepositoryImages\HeavyBid1_0Repository68e4a2db.rximgres")
                _element1261217568Info = New RepoItemInfo(Me, "Element1261217568", "element[@controlid='-1261217568']", 30000, Nothing, "25e2e5d8-476d-417b-aadb-39e339495b54")
            End Sub

            ''' <summary>
            ''' The Self item.
            ''' </summary>
            <RepositoryItem("e6f4104c-6f06-488c-ac35-02fa1ee32a38")> _
            Public Overridable ReadOnly Property Self As Ranorex.Form
                Get
                    Return _selfInfo.CreateAdapter(Of Ranorex.Form)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Self item info.
            ''' </summary>
            <RepositoryItemInfo("e6f4104c-6f06-488c-ac35-02fa1ee32a38")> _
            Public Overridable ReadOnly Property SelfInfo As RepoItemInfo
                Get
                    Return _selfInfo
                End Get
            End Property

            ''' <summary>
            ''' The Element1261217568 item.
            ''' </summary>
            <RepositoryItem("25e2e5d8-476d-417b-aadb-39e339495b54")> _
            Public Overridable ReadOnly Property Element1261217568 As Ranorex.Unknown
                Get
                    Return _element1261217568Info.CreateAdapter(Of Ranorex.Unknown)(True)
                End Get
            End Property

            ''' <summary>
            ''' The Element1261217568 item info.
            ''' </summary>
            <RepositoryItemInfo("25e2e5d8-476d-417b-aadb-39e339495b54")> _
            Public Overridable ReadOnly Property Element1261217568Info As RepoItemInfo
                Get
                    Return _element1261217568Info
                End Get
            End Property
        End Class
    End Class
End Namespace
