'//////////////////////////////////////////////////////////////////////////////
'
' This file was automatically generated by RANOREX.
' DO NOT MODIFY THIS FILE! It is regenerated by the designer.
' All your modifications will be lost!
' http://www.ranorex.com
'
'//////////////////////////////////////////////////////////////////////////////

Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Text.RegularExpressions
Imports System.Drawing
Imports System.Threading
Imports WinForms = System.Windows.Forms

Imports Ranorex
Imports Ranorex.Core
Imports Ranorex.Core.Testing
Imports Ranorex.Core.Repository

Namespace HeavyBid1._
    ''' <summary>
    '''The Recording recording.
    ''' </summary>
    <TestModule("de912ae9-0f9e-4dfa-b5dc-fda764e49c4a", ModuleType.Recording, 1)> _
    Partial Public Class Recording
        Implements ITestModule

        ''' <summary>
        ''' Holds an instance of the HeavyBid1_0Repository repository.
        ''' </summary>
        Public Shared repo as HeavyBid1_0Repository = HeavyBid1_0Repository.Instance

        Shared _instance as Recording = new Recording()

        ''' <summary>
        ''' Constructs a new instance.
        ''' </summary>
        Sub New()
        End Sub

        ''' <summary>
        ''' Gets a static instance of this recording.
        ''' </summary>
        Public Shared ReadOnly Property Instance As Recording
            Get
                Return _instance
            End Get
        End Property

#Region "Variables"

#End Region

        ''' <summary>
        ''' Starts the replay of the static recording <see cref="Instance"/>.
        ''' </summary>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")> _
        Public Shared Sub Start()
            TestModuleRunner.Run(Instance)
        End Sub

        ''' <summary>
        ''' Performs the playback of actions in this recording.
        ''' </summary>
        ''' <remarks>You should not call this method directly, instead pass the module
        ''' instance to the <see cref="TestModuleRunner.Run(Of ITestModule)"/> method
        ''' that will in turn invoke this method.</remarks>
        <System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")> _
        Sub Run() Implements ITestModule.Run
            Mouse.DefaultMoveTime = 300
            Keyboard.DefaultKeyPressTime = 100
            Delay.SpeedFactor = 1.00

            Init()

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://accessuh.uh.edu/login.php' with browser 'chrome' in normal mode.", new RecordItemIndex(0))
            Host.Current.OpenBrowser("https://accessuh.uh.edu/login.php", "chrome", "", False, False, False, False, False)
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'atjonakw{Tab}stra8{RShiftKey down}GARBAGE!{RShiftKey up}{Return}'.", new RecordItemIndex(1))
            Keyboard.Press("atjonakw{Tab}stra8{RShiftKey down}GARBAGE!{RShiftKey up}{Return}")
            Delay.Milliseconds(0)
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'AccessUHUniversityOfHoustonGoogl.Element1261217568' at 901;553.", repo.AccessUHUniversityOfHoustonGoogl.Element1261217568Info, new RecordItemIndex(2))
            repo.AccessUHUniversityOfHoustonGoogl.Element1261217568.Click("901;553")
            Delay.Milliseconds(200)
            
        End Sub

#Region "Image Feature Data"
#End Region

    End Class

End Namespace
