///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackupEstimates recording.
    /// </summary>
    [TestModule("cd57d786-1425-421b-9c5f-1052aee5c447", ModuleType.Recording, 1)]
    public partial class BackupEstimates : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static BackupEstimates instance = new BackupEstimates();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackupEstimates()
        {
            DefaultEstimates = "1-Bridge";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackupEstimates Instance
        {
            get { return instance; }
        }

#region Variables

        string _DefaultEstimates;

        /// <summary>
        /// Gets or sets the value of variable DefaultEstimates.
        /// </summary>
        [TestVariable("adb66d9b-4877-4cf5-b01a-983699df60d8")]
        public string DefaultEstimates
        {
            get { return _DefaultEstimates; }
            set { _DefaultEstimates = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidTabs.FileTab' at Center.", repo.HeavyBidTabs.FileTabInfo, new RecordItemIndex(0));
            repo.HeavyBidTabs.FileTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidTabs.ButtonBackupEstimate' at Center.", repo.HeavyBidTabs.ButtonBackupEstimateInfo, new RecordItemIndex(1));
            repo.HeavyBidTabs.ButtonBackupEstimate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBButtonDropdownOptions.BackupEstimateSingle' at Center.", repo.HBButtonDropdownOptions.BackupEstimateSingleInfo, new RecordItemIndex(2));
            repo.HBButtonDropdownOptions.BackupEstimateSingle.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackupEstimate.Button___' at Center.", repo.BackupEstimate.Button___Info, new RecordItemIndex(3));
            repo.BackupEstimate.Button___.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackupEstimateClass.ListExistingEstimates' at Center.", repo.BackupEstimateClass.ListExistingEstimatesInfo, new RecordItemIndex(4));
            repo.BackupEstimateClass.ListExistingEstimates.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DefaultEstimates'.", new RecordItemIndex(5));
            Keyboard.Press(DefaultEstimates);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EstimateSearch.ButtonOk' at Center.", repo.EstimateSearch.ButtonOkInfo, new RecordItemIndex(6));
            repo.EstimateSearch.ButtonOk.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackupEstimateClass.ButtonOk' at Center.", repo.BackupEstimateClass.ButtonOkInfo, new RecordItemIndex(7));
            repo.BackupEstimateClass.ButtonOk.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackupEstimate.ButtonFinish' at Center.", repo.BackupEstimate.ButtonFinishInfo, new RecordItemIndex(8));
            repo.BackupEstimate.ButtonFinish.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'HCSSBackupExists.ButtonOK' at Center.", repo.HCSSBackupExists.ButtonOKInfo, new RecordItemIndex(9));
                repo.HCSSBackupExists.ButtonOK.Click();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(9)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
