///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeShowRibbon recording.
    /// </summary>
    [TestModule("db99fbaa-ee00-4634-a8cf-5e650f8418f6", ModuleType.Recording, 1)]
    public partial class ChangeShowRibbon : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ChangeShowRibbon instance = new ChangeShowRibbon();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeShowRibbon()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeShowRibbon Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.HCSSIcon' at Center.", repo.HeavyBidApp.Buttons.HCSSIconInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Buttons.HCSSIcon.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeNotEqual (Checked!='Show Ribbon Bar') on item 'HBButtonDropdownOptions.ShowRibbonBar'.", repo.HBButtonDropdownOptions.ShowRibbonBarInfo, new RecordItemIndex(1));
            Validate.AttributeNotEqual(repo.HBButtonDropdownOptions.ShowRibbonBarInfo, "Checked", "Show Ribbon Bar");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBButtonDropdownOptions.ShowRibbonBar' at Center.", repo.HBButtonDropdownOptions.ShowRibbonBarInfo, new RecordItemIndex(2));
            repo.HBButtonDropdownOptions.ShowRibbonBar.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.HCSSIcon' at Center.", repo.HeavyBidApp.Buttons.HCSSIconInfo, new RecordItemIndex(3));
            repo.HeavyBidApp.Buttons.HCSSIcon.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HBButtonDropdownOptions.ShowRibbonBar'.", repo.HBButtonDropdownOptions.ShowRibbonBarInfo, new RecordItemIndex(4));
            Validate.Exists(repo.HBButtonDropdownOptions.ShowRibbonBarInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
