///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfirmHBWSInstallFinish recording.
    /// </summary>
    [TestModule("cf428a88-a1c6-4200-9ab2-22e40ed4c0ff", ModuleType.Recording, 1)]
    public partial class ConfirmHBWSInstallFinish : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ConfirmHBWSInstallFinish instance = new ConfirmHBWSInstallFinish();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfirmHBWSInstallFinish()
        {
            YearVersion = "2018.1";
            WSFilePath = "C:\\HeavyBidWS\\";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfirmHBWSInstallFinish Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable YearVersion.
        /// </summary>
        [TestVariable("368e7f48-9b0f-4a0d-a61a-3eb4d930ed90")]
        public string YearVersion
        {
            get { return repo.YearVersion; }
            set { repo.YearVersion = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable WSFilePath.
        /// </summary>
        [TestVariable("7837f9f6-ffe4-4d33-a291-857343197081")]
        public string WSFilePath
        {
            get { return repo.WSFilePath; }
            set { repo.WSFilePath = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // B.3
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nB.3\r\nValidating AttributeRegEx (Text~'[HeavyBid][Workstation]') on item 'HeavyBidWorkstationSetup.Titlebar'.", repo.HeavyBidWorkstationSetup.TitlebarInfo, new RecordItemIndex(0));
                Validate.Attribute(repo.HeavyBidWorkstationSetup.TitlebarInfo, "Text", new Regex("[HeavyBid][Workstation]"), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            // B.3
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nB.3\r\nValidating AttributeRegEx (Text~$YearVersion) on item 'HeavyBidWorkstationSetup.Titlebar'.", repo.HeavyBidWorkstationSetup.TitlebarInfo, new RecordItemIndex(1));
                Validate.Attribute(repo.HeavyBidWorkstationSetup.TitlebarInfo, "Text", new Regex(YearVersion), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            // ASK AUTOMATION
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nASK AUTOMATION\r\nValidating AttributeRegEx (Text~$WSFilePath) on item 'HeavyBidWorkstationSetup.TextBoxForValidation.OutputForFilePath'.", repo.HeavyBidWorkstationSetup.TextBoxForValidation.OutputForFilePathInfo, new RecordItemIndex(2));
                Validate.Attribute(repo.HeavyBidWorkstationSetup.TextBoxForValidation.OutputForFilePathInfo, "Text", new Regex(WSFilePath), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'HeavyBidWorkstationSetup.Buttons.ButtonInstall'", repo.HeavyBidWorkstationSetup.Buttons.ButtonInstallInfo, new ActionTimeout(60000), new RecordItemIndex(3));
            repo.HeavyBidWorkstationSetup.Buttons.ButtonInstallInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidWorkstationSetup.Buttons.ButtonInstall' at Center.", repo.HeavyBidWorkstationSetup.Buttons.ButtonInstallInfo, new RecordItemIndex(4));
            repo.HeavyBidWorkstationSetup.Buttons.ButtonInstall.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15m to exist. Associated repository item: 'HeavyBidWorkstationSetup.Buttons.ButtonFinish'", repo.HeavyBidWorkstationSetup.Buttons.ButtonFinishInfo, new ActionTimeout(900000), new RecordItemIndex(5));
            repo.HeavyBidWorkstationSetup.Buttons.ButtonFinishInfo.WaitForExists(900000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidWorkstationSetup.Buttons.ButtonFinish' at Center.", repo.HeavyBidWorkstationSetup.Buttons.ButtonFinishInfo, new RecordItemIndex(6));
            repo.HeavyBidWorkstationSetup.Buttons.ButtonFinish.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
