///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ExportToAccounting recording.
    /// </summary>
    [TestModule("199414ad-adf1-4143-a78c-006c091b5924", ModuleType.Recording, 1)]
    public partial class ExportToAccounting : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ExportToAccounting instance = new ExportToAccounting();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ExportToAccounting()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ExportToAccounting Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.ExchangeTab' at Center.", repo.HeavyBidApp.Tabs.ExchangeTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.ExchangeTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.Exchange.HJAndAccountingExport' at Center.", repo.HeavyBidApp.Buttons.Exchange.HJAndAccountingExportInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.Exchange.HJAndAccountingExport.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportToAccounting' at Center.", repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportToAccountingInfo, new RecordItemIndex(2));
            repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportToAccounting.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportButton' at Center.", repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportButtonInfo, new RecordItemIndex(3));
            repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExportButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'HBPopupScreens.FromExchangeButtons.ExportComplete.CompleteConfirmationText'.", repo.HBPopupScreens.FromExchangeButtons.ExportComplete.CompleteConfirmationTextInfo, new RecordItemIndex(4));
            Validate.Exists(repo.HBPopupScreens.FromExchangeButtons.ExportComplete.CompleteConfirmationTextInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.FromExchangeButtons.ExportComplete.OKButton' at Center.", repo.HBPopupScreens.FromExchangeButtons.ExportComplete.OKButtonInfo, new RecordItemIndex(5));
            repo.HBPopupScreens.FromExchangeButtons.ExportComplete.OKButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
