///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HB_INSTALL_AUTORepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("b36fe32b-c31b-4a2b-9886-acc9b1e6ac67")]
    public partial class HB_INSTALL_AUTORepository : RepoGenBaseFolder
    {
        static HB_INSTALL_AUTORepository instance = new HB_INSTALL_AUTORepository();
        HB_INSTALL_AUTORepositoryFolders.HeavyBidServerSetupAppFolder _heavybidserversetup;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidWorkstationSetupAppFolder _heavybidworkstationsetup;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidRegistrationAppFolder _heavybidregistration;
        HB_INSTALL_AUTORepositoryFolders.ActivateHeavyBidServerAppFolder _activateheavybidserver;
        HB_INSTALL_AUTORepositoryFolders.UserLoginAppFolder _userlogin;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidApplicationAppFolder _heavybidapplication;
        HB_INSTALL_AUTORepositoryFolders.ExitHeavyBidAppFolder _exitheavybid;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidServerFolderAppFolder _heavybidserverfolder;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidWSFolderAppFolder _heavybidwsfolder;
        HB_INSTALL_AUTORepositoryFolders.WindowsMenuBarAppFolder _windowsmenubar;
        HB_INSTALL_AUTORepositoryFolders.ProgramsAndFeaturesAppFolder _programsandfeatures;
        HB_INSTALL_AUTORepositoryFolders.HeavyBidUninstallAppFolder _heavybiduninstall;
        HB_INSTALL_AUTORepositoryFolders.WelcomeToHeavyBidScreenAppFolder _welcometoheavybidscreen;

        /// <summary>
        /// Gets the singleton class instance representing the HB_INSTALL_AUTORepository element repository.
        /// </summary>
        [RepositoryFolder("b36fe32b-c31b-4a2b-9886-acc9b1e6ac67")]
        public static HB_INSTALL_AUTORepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HB_INSTALL_AUTORepository() 
            : base("HB_INSTALL_AUTORepository", "/", null, 0, false, "b36fe32b-c31b-4a2b-9886-acc9b1e6ac67", ".\\RepositoryImages\\HB_INSTALL_AUTORepositoryb36fe32b.rximgres")
        {
            _heavybidserversetup = new HB_INSTALL_AUTORepositoryFolders.HeavyBidServerSetupAppFolder(this);
            _heavybidworkstationsetup = new HB_INSTALL_AUTORepositoryFolders.HeavyBidWorkstationSetupAppFolder(this);
            _heavybidregistration = new HB_INSTALL_AUTORepositoryFolders.HeavyBidRegistrationAppFolder(this);
            _activateheavybidserver = new HB_INSTALL_AUTORepositoryFolders.ActivateHeavyBidServerAppFolder(this);
            _userlogin = new HB_INSTALL_AUTORepositoryFolders.UserLoginAppFolder(this);
            _heavybidapplication = new HB_INSTALL_AUTORepositoryFolders.HeavyBidApplicationAppFolder(this);
            _exitheavybid = new HB_INSTALL_AUTORepositoryFolders.ExitHeavyBidAppFolder(this);
            _heavybidserverfolder = new HB_INSTALL_AUTORepositoryFolders.HeavyBidServerFolderAppFolder(this);
            _heavybidwsfolder = new HB_INSTALL_AUTORepositoryFolders.HeavyBidWSFolderAppFolder(this);
            _windowsmenubar = new HB_INSTALL_AUTORepositoryFolders.WindowsMenuBarAppFolder(this);
            _programsandfeatures = new HB_INSTALL_AUTORepositoryFolders.ProgramsAndFeaturesAppFolder(this);
            _heavybiduninstall = new HB_INSTALL_AUTORepositoryFolders.HeavyBidUninstallAppFolder(this);
            _welcometoheavybidscreen = new HB_INSTALL_AUTORepositoryFolders.WelcomeToHeavyBidScreenAppFolder(this);
        }

#region Variables

        string _NewVariable = "HeavyBidTrunk_2018-03-14_0042";

        /// <summary>
        /// Gets or sets the value of variable NewVariable.
        /// </summary>
        [TestVariable("0bbe00c3-2097-4c7c-b9b9-26d72daee7e7")]
        public string NewVariable
        {
            get { return _NewVariable; }
            set { _NewVariable = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b36fe32b-c31b-4a2b-9886-acc9b1e6ac67")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HeavyBidServerSetup folder.
        /// </summary>
        [RepositoryFolder("de34c2e0-f817-4a24-9a91-b1fb4eaa598a")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidServerSetupAppFolder HeavyBidServerSetup
        {
            get { return _heavybidserversetup; }
        }

        /// <summary>
        /// The HeavyBidWorkstationSetup folder.
        /// </summary>
        [RepositoryFolder("88a24b5a-93b2-4dac-b8ad-8e0a11616d12")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidWorkstationSetupAppFolder HeavyBidWorkstationSetup
        {
            get { return _heavybidworkstationsetup; }
        }

        /// <summary>
        /// The HeavyBidRegistration folder.
        /// </summary>
        [RepositoryFolder("bbd82d23-584f-4b0c-801e-cd4629776ace")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidRegistrationAppFolder HeavyBidRegistration
        {
            get { return _heavybidregistration; }
        }

        /// <summary>
        /// The ActivateHeavyBidServer folder.
        /// </summary>
        [RepositoryFolder("45ccb5b4-0945-4143-924e-3e995615fa25")]
        public virtual HB_INSTALL_AUTORepositoryFolders.ActivateHeavyBidServerAppFolder ActivateHeavyBidServer
        {
            get { return _activateheavybidserver; }
        }

        /// <summary>
        /// The UserLogin folder.
        /// </summary>
        [RepositoryFolder("c64ad0bd-b657-4e67-903c-13b024628ec5")]
        public virtual HB_INSTALL_AUTORepositoryFolders.UserLoginAppFolder UserLogin
        {
            get { return _userlogin; }
        }

        /// <summary>
        /// The HeavyBidApplication folder.
        /// </summary>
        [RepositoryFolder("2f898f27-5ad8-489e-9722-e1d9c63f5289")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidApplicationAppFolder HeavyBidApplication
        {
            get { return _heavybidapplication; }
        }

        /// <summary>
        /// The ExitHeavyBid folder.
        /// </summary>
        [RepositoryFolder("c96d6789-b8f5-40dc-a7e8-56c5eed0baf1")]
        public virtual HB_INSTALL_AUTORepositoryFolders.ExitHeavyBidAppFolder ExitHeavyBid
        {
            get { return _exitheavybid; }
        }

        /// <summary>
        /// The HeavyBidServerFolder folder.
        /// </summary>
        [RepositoryFolder("ab0721fe-a94f-44e5-b9f6-db7020e9c20a")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidServerFolderAppFolder HeavyBidServerFolder
        {
            get { return _heavybidserverfolder; }
        }

        /// <summary>
        /// The HeavyBidWSFolder folder.
        /// </summary>
        [RepositoryFolder("8049599b-eeac-406c-98df-c705973311d8")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidWSFolderAppFolder HeavyBidWSFolder
        {
            get { return _heavybidwsfolder; }
        }

        /// <summary>
        /// The WindowsMenuBar folder.
        /// </summary>
        [RepositoryFolder("61625f19-ede6-4d77-b833-f1030fee1a3c")]
        public virtual HB_INSTALL_AUTORepositoryFolders.WindowsMenuBarAppFolder WindowsMenuBar
        {
            get { return _windowsmenubar; }
        }

        /// <summary>
        /// The ProgramsAndFeatures folder.
        /// </summary>
        [RepositoryFolder("bb83f234-7f01-4a6b-9b28-c7005b669ec4")]
        public virtual HB_INSTALL_AUTORepositoryFolders.ProgramsAndFeaturesAppFolder ProgramsAndFeatures
        {
            get { return _programsandfeatures; }
        }

        /// <summary>
        /// The HeavyBidUninstall folder.
        /// </summary>
        [RepositoryFolder("8e490430-7c24-4311-bae2-b5cb60265e78")]
        public virtual HB_INSTALL_AUTORepositoryFolders.HeavyBidUninstallAppFolder HeavyBidUninstall
        {
            get { return _heavybiduninstall; }
        }

        /// <summary>
        /// The WelcomeToHeavyBidScreen folder.
        /// </summary>
        [RepositoryFolder("18f7566c-43cf-4700-b584-eaabae46f352")]
        public virtual HB_INSTALL_AUTORepositoryFolders.WelcomeToHeavyBidScreenAppFolder WelcomeToHeavyBidScreen
        {
            get { return _welcometoheavybidscreen; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class HB_INSTALL_AUTORepositoryFolders
    {
        /// <summary>
        /// The HeavyBidServerSetupAppFolder folder.
        /// </summary>
        [RepositoryFolder("de34c2e0-f817-4a24-9a91-b1fb4eaa598a")]
        public partial class HeavyBidServerSetupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _iacceptthetermsinthelicenseagreemInfo;
            RepoItemInfo _multiusermultipleuserscanworkintInfo;
            RepoItemInfo _buttoninstallInfo;
            RepoItemInfo _buttonfinishInfo;
            RepoItemInfo _buttonyesInfo;
            RepoItemInfo _serverinstalltitleInfo;

            /// <summary>
            /// Creates a new HeavyBidServerSetup  folder.
            /// </summary>
            public HeavyBidServerSetupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidServerSetup", "/form[@title~'[HeavyBid][Setup]']", parentFolder, 30000, null, true, "de34c2e0-f817-4a24-9a91-b1fb4eaa598a", "")
            {
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Next']", 30000, null, "d5871a5b-28dc-49bc-ab19-510a037a9d94");
                _iacceptthetermsinthelicenseagreemInfo = new RepoItemInfo(this, "IAcceptTheTermsInTheLicenseAgreem", "checkbox[@text~'[agree][terms]']", 30000, null, "0b9fc09c-2aa6-473e-b588-b28d927bed0c");
                _multiusermultipleuserscanworkintInfo = new RepoItemInfo(this, "MultiUserMultipleUsersCanWorkInT", "?/?/radiobutton[@text~'^[Multi-user]']", 30000, null, "87f3d72a-a7d3-4b0f-9b41-5932103d923d");
                _buttoninstallInfo = new RepoItemInfo(this, "ButtonInstall", "button[@text='&Install']", 30000, null, "13bbdbc5-9df3-4bf6-8e96-1f4c1a5c6bda");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", "button[@text='&Finish']", 30000, null, "f6d583e3-44b4-4f93-b8a3-91c915c2c48c");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='Yes']", 30000, null, "1cbaddb5-161e-467e-ae75-42781f0dd64d");
                _serverinstalltitleInfo = new RepoItemInfo(this, "ServerInstallTitle", "titlebar", 30000, null, "7fdd31f1-bfea-4860-8dd4-e0712deabac9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("de34c2e0-f817-4a24-9a91-b1fb4eaa598a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("de34c2e0-f817-4a24-9a91-b1fb4eaa598a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("d5871a5b-28dc-49bc-ab19-510a037a9d94")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("d5871a5b-28dc-49bc-ab19-510a037a9d94")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item.
            /// </summary>
            [RepositoryItem("0b9fc09c-2aa6-473e-b588-b28d927bed0c")]
            public virtual Ranorex.CheckBox IAcceptTheTermsInTheLicenseAgreem
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item info.
            /// </summary>
            [RepositoryItemInfo("0b9fc09c-2aa6-473e-b588-b28d927bed0c")]
            public virtual RepoItemInfo IAcceptTheTermsInTheLicenseAgreemInfo
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo;
                }
            }

            /// <summary>
            /// The MultiUserMultipleUsersCanWorkInT item.
            /// </summary>
            [RepositoryItem("87f3d72a-a7d3-4b0f-9b41-5932103d923d")]
            public virtual Ranorex.RadioButton MultiUserMultipleUsersCanWorkInT
            {
                get
                {
                    return _multiusermultipleuserscanworkintInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MultiUserMultipleUsersCanWorkInT item info.
            /// </summary>
            [RepositoryItemInfo("87f3d72a-a7d3-4b0f-9b41-5932103d923d")]
            public virtual RepoItemInfo MultiUserMultipleUsersCanWorkInTInfo
            {
                get
                {
                    return _multiusermultipleuserscanworkintInfo;
                }
            }

            /// <summary>
            /// The ButtonInstall item.
            /// </summary>
            [RepositoryItem("13bbdbc5-9df3-4bf6-8e96-1f4c1a5c6bda")]
            public virtual Ranorex.Button ButtonInstall
            {
                get
                {
                    return _buttoninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonInstall item info.
            /// </summary>
            [RepositoryItemInfo("13bbdbc5-9df3-4bf6-8e96-1f4c1a5c6bda")]
            public virtual RepoItemInfo ButtonInstallInfo
            {
                get
                {
                    return _buttoninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("f6d583e3-44b4-4f93-b8a3-91c915c2c48c")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("f6d583e3-44b4-4f93-b8a3-91c915c2c48c")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("1cbaddb5-161e-467e-ae75-42781f0dd64d")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("1cbaddb5-161e-467e-ae75-42781f0dd64d")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }

            /// <summary>
            /// The ServerInstallTitle item.
            /// </summary>
            [RepositoryItem("7fdd31f1-bfea-4860-8dd4-e0712deabac9")]
            public virtual Ranorex.TitleBar ServerInstallTitle
            {
                get
                {
                    return _serverinstalltitleInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The ServerInstallTitle item info.
            /// </summary>
            [RepositoryItemInfo("7fdd31f1-bfea-4860-8dd4-e0712deabac9")]
            public virtual RepoItemInfo ServerInstallTitleInfo
            {
                get
                {
                    return _serverinstalltitleInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidWorkstationSetupAppFolder folder.
        /// </summary>
        [RepositoryFolder("88a24b5a-93b2-4dac-b8ad-8e0a11616d12")]
        public partial class HeavyBidWorkstationSetupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonnextInfo;
            RepoItemInfo _buttoninstallInfo;
            RepoItemInfo _buttonfinishInfo;

            /// <summary>
            /// Creates a new HeavyBidWorkstationSetup  folder.
            /// </summary>
            public HeavyBidWorkstationSetupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidWorkstationSetup", "/form[@title~'[HeavyBid][Workstation]']", parentFolder, 30000, null, true, "88a24b5a-93b2-4dac-b8ad-8e0a11616d12", "")
            {
                _buttonnextInfo = new RepoItemInfo(this, "ButtonNext", "button[@text='&Next']", 30000, null, "6d694e30-aaad-4df4-b475-ef46ac6418c2");
                _buttoninstallInfo = new RepoItemInfo(this, "ButtonInstall", "button[@text='&Install']", 30000, null, "2ad4563d-4122-4526-9122-cb80ba07afdf");
                _buttonfinishInfo = new RepoItemInfo(this, "ButtonFinish", "button[@text='&Finish']", 30000, null, "5ef2d410-9f3c-4f2b-8e00-0010d1e06303");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88a24b5a-93b2-4dac-b8ad-8e0a11616d12")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88a24b5a-93b2-4dac-b8ad-8e0a11616d12")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonNext item.
            /// </summary>
            [RepositoryItem("6d694e30-aaad-4df4-b475-ef46ac6418c2")]
            public virtual Ranorex.Button ButtonNext
            {
                get
                {
                    return _buttonnextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonNext item info.
            /// </summary>
            [RepositoryItemInfo("6d694e30-aaad-4df4-b475-ef46ac6418c2")]
            public virtual RepoItemInfo ButtonNextInfo
            {
                get
                {
                    return _buttonnextInfo;
                }
            }

            /// <summary>
            /// The ButtonInstall item.
            /// </summary>
            [RepositoryItem("2ad4563d-4122-4526-9122-cb80ba07afdf")]
            public virtual Ranorex.Button ButtonInstall
            {
                get
                {
                    return _buttoninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonInstall item info.
            /// </summary>
            [RepositoryItemInfo("2ad4563d-4122-4526-9122-cb80ba07afdf")]
            public virtual RepoItemInfo ButtonInstallInfo
            {
                get
                {
                    return _buttoninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonFinish item.
            /// </summary>
            [RepositoryItem("5ef2d410-9f3c-4f2b-8e00-0010d1e06303")]
            public virtual Ranorex.Button ButtonFinish
            {
                get
                {
                    return _buttonfinishInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonFinish item info.
            /// </summary>
            [RepositoryItemInfo("5ef2d410-9f3c-4f2b-8e00-0010d1e06303")]
            public virtual RepoItemInfo ButtonFinishInfo
            {
                get
                {
                    return _buttonfinishInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidRegistrationAppFolder folder.
        /// </summary>
        [RepositoryFolder("bbd82d23-584f-4b0c-801e-cd4629776ace")]
        public partial class HeavyBidRegistrationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _checkInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _registrationentryInfo;

            /// <summary>
            /// Creates a new HeavyBidRegistration  folder.
            /// </summary>
            public HeavyBidRegistrationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidRegistration", "/form[@title~'[HeavyBid][Registration]']", parentFolder, 30000, null, true, "bbd82d23-584f-4b0c-801e-cd4629776ace", "")
            {
                _checkInfo = new RepoItemInfo(this, "Check", ".//button[@text='Check']", 30000, null, "7965edbb-7fdd-4cfd-be12-92582177ed8e");
                _submitInfo = new RepoItemInfo(this, "Submit", ".//button[@text='Submit']", 30000, null, "c61c6cd8-dab4-4f52-914d-90233ee9b6d2");
                _registrationentryInfo = new RepoItemInfo(this, "RegistrationEntry", "element[1]/element[@class='DFentry']", 30000, null, "588d4131-a392-43df-92cf-4b8c1e94a82f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bbd82d23-584f-4b0c-801e-cd4629776ace")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bbd82d23-584f-4b0c-801e-cd4629776ace")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Check item.
            /// </summary>
            [RepositoryItem("7965edbb-7fdd-4cfd-be12-92582177ed8e")]
            public virtual Ranorex.Button Check
            {
                get
                {
                    return _checkInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Check item info.
            /// </summary>
            [RepositoryItemInfo("7965edbb-7fdd-4cfd-be12-92582177ed8e")]
            public virtual RepoItemInfo CheckInfo
            {
                get
                {
                    return _checkInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("c61c6cd8-dab4-4f52-914d-90233ee9b6d2")]
            public virtual Ranorex.Button Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("c61c6cd8-dab4-4f52-914d-90233ee9b6d2")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The RegistrationEntry item.
            /// </summary>
            [RepositoryItem("588d4131-a392-43df-92cf-4b8c1e94a82f")]
            public virtual Ranorex.Unknown RegistrationEntry
            {
                get
                {
                    return _registrationentryInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The RegistrationEntry item info.
            /// </summary>
            [RepositoryItemInfo("588d4131-a392-43df-92cf-4b8c1e94a82f")]
            public virtual RepoItemInfo RegistrationEntryInfo
            {
                get
                {
                    return _registrationentryInfo;
                }
            }
        }

        /// <summary>
        /// The ActivateHeavyBidServerAppFolder folder.
        /// </summary>
        [RepositoryFolder("45ccb5b4-0945-4143-924e-3e995615fa25")]
        public partial class ActivateHeavyBidServerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _replacetheexistingproductionserverwInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new ActivateHeavyBidServer  folder.
            /// </summary>
            public ActivateHeavyBidServerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ActivateHeavyBidServer", "/form[@title~'[Activate][HeavyBid][Server]']", parentFolder, 30000, null, true, "45ccb5b4-0945-4143-924e-3e995615fa25", "")
            {
                _replacetheexistingproductionserverwInfo = new RepoItemInfo(this, "ReplaceTheExistingProductionServerW", ".//radiobutton[@text~'[Replace][existing][Production]']", 30000, null, "0c89c5e3-6afc-4e9e-b166-24682fcb9371");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@text='OK']", 30000, null, "053b5249-e733-4708-a4c8-7dfd694a7c96");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("45ccb5b4-0945-4143-924e-3e995615fa25")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("45ccb5b4-0945-4143-924e-3e995615fa25")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ReplaceTheExistingProductionServerW item.
            /// </summary>
            [RepositoryItem("0c89c5e3-6afc-4e9e-b166-24682fcb9371")]
            public virtual Ranorex.RadioButton ReplaceTheExistingProductionServerW
            {
                get
                {
                    return _replacetheexistingproductionserverwInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The ReplaceTheExistingProductionServerW item info.
            /// </summary>
            [RepositoryItemInfo("0c89c5e3-6afc-4e9e-b166-24682fcb9371")]
            public virtual RepoItemInfo ReplaceTheExistingProductionServerWInfo
            {
                get
                {
                    return _replacetheexistingproductionserverwInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("053b5249-e733-4708-a4c8-7dfd694a7c96")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("053b5249-e733-4708-a4c8-7dfd694a7c96")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The UserLoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("c64ad0bd-b657-4e67-903c-13b024628ec5")]
        public partial class UserLoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _usernumberentryInfo;

            /// <summary>
            /// Creates a new UserLogin  folder.
            /// </summary>
            public UserLoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("UserLogin", "/form[@title='User Login']", parentFolder, 30000, null, true, "c64ad0bd-b657-4e67-903c-13b024628ec5", "")
            {
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", ".//?/?/button[@text='OK']", 30000, null, "79d62785-563a-4181-b4d1-e1f5aedea505");
                _usernumberentryInfo = new RepoItemInfo(this, "UserNumberEntry", ".//button[@accessiblename='...']/../..", 30000, null, "5535fdd1-6eaf-4196-9ddd-20e000736e3c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c64ad0bd-b657-4e67-903c-13b024628ec5")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c64ad0bd-b657-4e67-903c-13b024628ec5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("79d62785-563a-4181-b4d1-e1f5aedea505")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("79d62785-563a-4181-b4d1-e1f5aedea505")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The UserNumberEntry item.
            /// </summary>
            [RepositoryItem("5535fdd1-6eaf-4196-9ddd-20e000736e3c")]
            public virtual Ranorex.Unknown UserNumberEntry
            {
                get
                {
                    return _usernumberentryInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The UserNumberEntry item info.
            /// </summary>
            [RepositoryItemInfo("5535fdd1-6eaf-4196-9ddd-20e000736e3c")]
            public virtual RepoItemInfo UserNumberEntryInfo
            {
                get
                {
                    return _usernumberentryInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("2f898f27-5ad8-489e-9722-e1d9c63f5289")]
        public partial class HeavyBidApplicationAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new HeavyBidApplication  folder.
            /// </summary>
            public HeavyBidApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidApplication", "/form[@title~'HB']", parentFolder, 30000, null, true, "2f898f27-5ad8-489e-9722-e1d9c63f5289", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f898f27-5ad8-489e-9722-e1d9c63f5289")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f898f27-5ad8-489e-9722-e1d9c63f5289")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The ExitHeavyBidAppFolder folder.
        /// </summary>
        [RepositoryFolder("c96d6789-b8f5-40dc-a7e8-56c5eed0baf1")]
        public partial class ExitHeavyBidAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new ExitHeavyBid  folder.
            /// </summary>
            public ExitHeavyBidAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExitHeavyBid", "/form[@title~'[Exit][HeavyBid]']", parentFolder, 30000, null, true, "c96d6789-b8f5-40dc-a7e8-56c5eed0baf1", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 30000, null, "a8c789b1-5120-4456-bde6-28ab276d37f5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c96d6789-b8f5-40dc-a7e8-56c5eed0baf1")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c96d6789-b8f5-40dc-a7e8-56c5eed0baf1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("a8c789b1-5120-4456-bde6-28ab276d37f5")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("a8c789b1-5120-4456-bde6-28ab276d37f5")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidServerFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("ab0721fe-a94f-44e5-b9f6-db7020e9c20a")]
        public partial class HeavyBidServerFolderAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new HeavyBidServerFolder  folder.
            /// </summary>
            public HeavyBidServerFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidServerFolder", "/form[@title='HeavyBid']", parentFolder, 30000, null, true, "ab0721fe-a94f-44e5-b9f6-db7020e9c20a", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ab0721fe-a94f-44e5-b9f6-db7020e9c20a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ab0721fe-a94f-44e5-b9f6-db7020e9c20a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidWSFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("8049599b-eeac-406c-98df-c705973311d8")]
        public partial class HeavyBidWSFolderAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new HeavyBidWSFolder  folder.
            /// </summary>
            public HeavyBidWSFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidWSFolder", "/form[@title='HeavyBidWS']", parentFolder, 30000, null, true, "8049599b-eeac-406c-98df-c705973311d8", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8049599b-eeac-406c-98df-c705973311d8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8049599b-eeac-406c-98df-c705973311d8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The WindowsMenuBarAppFolder folder.
        /// </summary>
        [RepositoryFolder("61625f19-ede6-4d77-b833-f1030fee1a3c")]
        public partial class WindowsMenuBarAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hcsscrystalxiintegrationinstallsInfo;
            RepoItemInfo _microsoftsqlserver2012nativeclientInfo;
            RepoItemInfo _heavybidfinishinstallInfo;

            /// <summary>
            /// Creates a new WindowsMenuBar  folder.
            /// </summary>
            public WindowsMenuBarAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WindowsMenuBar", "/menubar", parentFolder, 30000, null, true, "61625f19-ede6-4d77-b833-f1030fee1a3c", "")
            {
                _hcsscrystalxiintegrationinstallsInfo = new RepoItemInfo(this, "HCSSCrystalXIIntegrationInstallS", ".////button[@accessiblename~'HCSS']", 30000, null, "43f5474f-3794-45d9-8f09-5d79fa829cd3");
                _microsoftsqlserver2012nativeclientInfo = new RepoItemInfo(this, "MicrosoftSQLServer2012NativeClient", ".////button[@accessiblename~'Microsoft SQL']", 30000, null, "6942dacc-3d93-4c04-b266-4e2483f821da");
                _heavybidfinishinstallInfo = new RepoItemInfo(this, "HeavyBidFinishInstall", ".////button[@accessiblename~'HeavyBid']", 30000, null, "73e771ee-4c82-4aa9-b7eb-f38f8137cb9f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("61625f19-ede6-4d77-b833-f1030fee1a3c")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("61625f19-ede6-4d77-b833-f1030fee1a3c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegrationInstallS item.
            /// </summary>
            [RepositoryItem("43f5474f-3794-45d9-8f09-5d79fa829cd3")]
            public virtual Ranorex.Button HCSSCrystalXIIntegrationInstallS
            {
                get
                {
                    return _hcsscrystalxiintegrationinstallsInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegrationInstallS item info.
            /// </summary>
            [RepositoryItemInfo("43f5474f-3794-45d9-8f09-5d79fa829cd3")]
            public virtual RepoItemInfo HCSSCrystalXIIntegrationInstallSInfo
            {
                get
                {
                    return _hcsscrystalxiintegrationinstallsInfo;
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item.
            /// </summary>
            [RepositoryItem("6942dacc-3d93-4c04-b266-4e2483f821da")]
            public virtual Ranorex.Button MicrosoftSQLServer2012NativeClient
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item info.
            /// </summary>
            [RepositoryItemInfo("6942dacc-3d93-4c04-b266-4e2483f821da")]
            public virtual RepoItemInfo MicrosoftSQLServer2012NativeClientInfo
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo;
                }
            }

            /// <summary>
            /// The HeavyBidFinishInstall item.
            /// </summary>
            [RepositoryItem("73e771ee-4c82-4aa9-b7eb-f38f8137cb9f")]
            public virtual Ranorex.Button HeavyBidFinishInstall
            {
                get
                {
                    return _heavybidfinishinstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The HeavyBidFinishInstall item info.
            /// </summary>
            [RepositoryItemInfo("73e771ee-4c82-4aa9-b7eb-f38f8137cb9f")]
            public virtual RepoItemInfo HeavyBidFinishInstallInfo
            {
                get
                {
                    return _heavybidfinishinstallInfo;
                }
            }
        }

        /// <summary>
        /// The ProgramsAndFeaturesAppFolder folder.
        /// </summary>
        [RepositoryFolder("bb83f234-7f01-4a6b-9b28-c7005b669ec4")]
        public partial class ProgramsAndFeaturesAppFolder : RepoGenBaseFolder
        {
            HB_INSTALL_AUTORepositoryFolders.Row0Folder _row0;
            RepoItemInfo _buttonuninstallInfo;
            RepoItemInfo _buttonyesInfo;
            RepoItemInfo _buttinuninstallorchangeInfo;
            RepoItemInfo _searcheditboxInfo;

            /// <summary>
            /// Creates a new ProgramsAndFeatures  folder.
            /// </summary>
            public ProgramsAndFeaturesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProgramsAndFeatures", "/form[@title~'Programs and Features']", parentFolder, 30000, null, true, "bb83f234-7f01-4a6b-9b28-c7005b669ec4", "")
            {
                _row0 = new HB_INSTALL_AUTORepositoryFolders.Row0Folder(this);
                _buttonuninstallInfo = new RepoItemInfo(this, "ButtonUninstall", ".//container[@automationid='FolderLayoutContainer']/container[@classname='Element']/toolbar[@automationid='FolderBandModuleInner']/button[@automationid='{3E2267F1-30BD-489B-9DD6-2887121113E8}']", 30000, null, "8e655133-0f49-4357-ab46-e1f07390400d");
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "?/?/element[@instance='0']/button[@text='&Yes']", 30000, null, "3efc40c1-ea5d-4004-985f-366e7e176dc9");
                _buttinuninstallorchangeInfo = new RepoItemInfo(this, "ButtinUninstallOrChange", ".//container[@automationid='FolderLayoutContainer']/container[@classname='Element']/toolbar[@automationid='FolderBandModuleInner']/button[@automationid='{D57F5067-EB9C-4863-B510-FC2C6A710454}']", 30000, null, "71cea4ec-b070-4408-90bc-44a4c19e08d6");
                _searcheditboxInfo = new RepoItemInfo(this, "SearchEditBox", "?/?/?/?/element[@class='Search Box']", 30000, null, "9c992ed7-95b4-43ac-b064-7b105340fbb8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bb83f234-7f01-4a6b-9b28-c7005b669ec4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bb83f234-7f01-4a6b-9b28-c7005b669ec4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonUninstall item.
            /// </summary>
            [RepositoryItem("8e655133-0f49-4357-ab46-e1f07390400d")]
            public virtual Ranorex.Button ButtonUninstall
            {
                get
                {
                    return _buttonuninstallInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonUninstall item info.
            /// </summary>
            [RepositoryItemInfo("8e655133-0f49-4357-ab46-e1f07390400d")]
            public virtual RepoItemInfo ButtonUninstallInfo
            {
                get
                {
                    return _buttonuninstallInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("3efc40c1-ea5d-4004-985f-366e7e176dc9")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("3efc40c1-ea5d-4004-985f-366e7e176dc9")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }

            /// <summary>
            /// The ButtinUninstallOrChange item.
            /// </summary>
            [RepositoryItem("71cea4ec-b070-4408-90bc-44a4c19e08d6")]
            public virtual Ranorex.Button ButtinUninstallOrChange
            {
                get
                {
                    return _buttinuninstallorchangeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtinUninstallOrChange item info.
            /// </summary>
            [RepositoryItemInfo("71cea4ec-b070-4408-90bc-44a4c19e08d6")]
            public virtual RepoItemInfo ButtinUninstallOrChangeInfo
            {
                get
                {
                    return _buttinuninstallorchangeInfo;
                }
            }

            /// <summary>
            /// The SearchEditBox item.
            /// </summary>
            [RepositoryItem("9c992ed7-95b4-43ac-b064-7b105340fbb8")]
            public virtual Ranorex.Unknown SearchEditBox
            {
                get
                {
                    return _searcheditboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SearchEditBox item info.
            /// </summary>
            [RepositoryItemInfo("9c992ed7-95b4-43ac-b064-7b105340fbb8")]
            public virtual RepoItemInfo SearchEditBoxInfo
            {
                get
                {
                    return _searcheditboxInfo;
                }
            }

            /// <summary>
            /// The Row0 folder.
            /// </summary>
            [RepositoryFolder("537a4c93-ac0a-47f6-a3ce-eafa40b9e810")]
            public virtual HB_INSTALL_AUTORepositoryFolders.Row0Folder Row0
            {
                get { return _row0; }
            }
        }

        /// <summary>
        /// The Row0Folder folder.
        /// </summary>
        [RepositoryFolder("537a4c93-ac0a-47f6-a3ce-eafa40b9e810")]
        public partial class Row0Folder : RepoGenBaseFolder
        {
            RepoItemInfo _heavybidworkstationInfo;
            RepoItemInfo _hcsscrystalxiintegrationInfo;
            RepoItemInfo _microsoftsqlserver2012nativeclientInfo;

            /// <summary>
            /// Creates a new Row0  folder.
            /// </summary>
            public Row0Folder(RepoGenBaseFolder parentFolder) :
                    base("Row0", ".//container[@caption='ShellView']/table[@controlid='1']/row[@index>='0']", parentFolder, 30000, null, false, "537a4c93-ac0a-47f6-a3ce-eafa40b9e810", "")
            {
                _heavybidworkstationInfo = new RepoItemInfo(this, "HeavyBidWorkstation", "cell[@text='HeavyBid Workstation']", 30000, null, "be61d9e1-da51-4fdc-8689-3e54667d17f7");
                _hcsscrystalxiintegrationInfo = new RepoItemInfo(this, "HCSSCrystalXIIntegration", "cell[@text~'^HCSS\\ -\\ Crystal\\ XI\\ Integra']", 30000, null, "61de3bb2-d64b-4cdd-8275-e2d0d84b9fef");
                _microsoftsqlserver2012nativeclientInfo = new RepoItemInfo(this, "MicrosoftSQLServer2012NativeClient", "cell[@text~'^Microsoft\\ SQL\\ Server\\ 2012']", 30000, null, "084bd652-eb81-4192-901d-c5734d7d24ec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("537a4c93-ac0a-47f6-a3ce-eafa40b9e810")]
            public virtual Ranorex.Row Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("537a4c93-ac0a-47f6-a3ce-eafa40b9e810")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HeavyBidWorkstation item.
            /// </summary>
            [RepositoryItem("be61d9e1-da51-4fdc-8689-3e54667d17f7")]
            public virtual Ranorex.Cell HeavyBidWorkstation
            {
                get
                {
                    return _heavybidworkstationInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The HeavyBidWorkstation item info.
            /// </summary>
            [RepositoryItemInfo("be61d9e1-da51-4fdc-8689-3e54667d17f7")]
            public virtual RepoItemInfo HeavyBidWorkstationInfo
            {
                get
                {
                    return _heavybidworkstationInfo;
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegration item.
            /// </summary>
            [RepositoryItem("61de3bb2-d64b-4cdd-8275-e2d0d84b9fef")]
            public virtual Ranorex.Cell HCSSCrystalXIIntegration
            {
                get
                {
                    return _hcsscrystalxiintegrationInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegration item info.
            /// </summary>
            [RepositoryItemInfo("61de3bb2-d64b-4cdd-8275-e2d0d84b9fef")]
            public virtual RepoItemInfo HCSSCrystalXIIntegrationInfo
            {
                get
                {
                    return _hcsscrystalxiintegrationInfo;
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item.
            /// </summary>
            [RepositoryItem("084bd652-eb81-4192-901d-c5734d7d24ec")]
            public virtual Ranorex.Cell MicrosoftSQLServer2012NativeClient
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item info.
            /// </summary>
            [RepositoryItemInfo("084bd652-eb81-4192-901d-c5734d7d24ec")]
            public virtual RepoItemInfo MicrosoftSQLServer2012NativeClientInfo
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidUninstallAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e490430-7c24-4311-bae2-b5cb60265e78")]
        public partial class HeavyBidUninstallAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new HeavyBidUninstall  folder.
            /// </summary>
            public HeavyBidUninstallAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidUninstall", "/form[@title='HeavyBid Uninstall']", parentFolder, 30000, null, true, "8e490430-7c24-4311-bae2-b5cb60265e78", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 30000, null, "f95b68e9-f4de-45e8-968f-0ac4f388600c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e490430-7c24-4311-bae2-b5cb60265e78")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e490430-7c24-4311-bae2-b5cb60265e78")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("f95b68e9-f4de-45e8-968f-0ac4f388600c")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("f95b68e9-f4de-45e8-968f-0ac4f388600c")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

        /// <summary>
        /// The WelcomeToHeavyBidScreenAppFolder folder.
        /// </summary>
        [RepositoryFolder("18f7566c-43cf-4700-b584-eaabae46f352")]
        public partial class WelcomeToHeavyBidScreenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _openestimatebuttonInfo;
            RepoItemInfo _welcometoheavybid20181Info;
            RepoItemInfo _createnewestimatebuttonInfo;
            RepoItemInfo _openexistingestimatebuttonInfo;

            /// <summary>
            /// Creates a new WelcomeToHeavyBidScreen  folder.
            /// </summary>
            public WelcomeToHeavyBidScreenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeToHeavyBidScreen", "/form[@title~'[Welcome][HeavyBid]']", parentFolder, 30000, null, true, "18f7566c-43cf-4700-b584-eaabae46f352", "")
            {
                _openestimatebuttonInfo = new RepoItemInfo(this, "OpenEstimateButton", "element[1]/element[@class='DFbutton']/?/button[@accessiblerole='PushButton']", 30000, null, "23d83cf4-b26a-4fbb-800d-60cd8193746b");
                _welcometoheavybid20181Info = new RepoItemInfo(this, "WelcomeToHeavyBid20181", "titlebar[@text~'[Welcome][HeavyBid]']", 30000, null, "617ed1c7-aa27-48e2-947b-cfe1ac5dc24f");
                _createnewestimatebuttonInfo = new RepoItemInfo(this, "CreateNewEstimateButton", "element[6]/element[@class='DFbutton']/?/button[@accessiblerole='PushButton']", 30000, null, "f362dc7e-4a8f-4de5-b2b9-497185d51104");
                _openexistingestimatebuttonInfo = new RepoItemInfo(this, "OpenExistingEstimateButton", "element[7]/element[@class='DFbutton']/?/button[@accessiblerole='PushButton']", 30000, null, "e0f87a37-a2f4-40b5-82e3-dc421eb4699c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("18f7566c-43cf-4700-b584-eaabae46f352")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("18f7566c-43cf-4700-b584-eaabae46f352")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OpenEstimateButton item.
            /// </summary>
            [RepositoryItem("23d83cf4-b26a-4fbb-800d-60cd8193746b")]
            public virtual Ranorex.Button OpenEstimateButton
            {
                get
                {
                    return _openestimatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenEstimateButton item info.
            /// </summary>
            [RepositoryItemInfo("23d83cf4-b26a-4fbb-800d-60cd8193746b")]
            public virtual RepoItemInfo OpenEstimateButtonInfo
            {
                get
                {
                    return _openestimatebuttonInfo;
                }
            }

            /// <summary>
            /// The WelcomeToHeavyBid20181 item.
            /// </summary>
            [RepositoryItem("617ed1c7-aa27-48e2-947b-cfe1ac5dc24f")]
            public virtual Ranorex.TitleBar WelcomeToHeavyBid20181
            {
                get
                {
                    return _welcometoheavybid20181Info.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The WelcomeToHeavyBid20181 item info.
            /// </summary>
            [RepositoryItemInfo("617ed1c7-aa27-48e2-947b-cfe1ac5dc24f")]
            public virtual RepoItemInfo WelcomeToHeavyBid20181Info
            {
                get
                {
                    return _welcometoheavybid20181Info;
                }
            }

            /// <summary>
            /// The CreateNewEstimateButton item.
            /// </summary>
            [RepositoryItem("f362dc7e-4a8f-4de5-b2b9-497185d51104")]
            public virtual Ranorex.Button CreateNewEstimateButton
            {
                get
                {
                    return _createnewestimatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CreateNewEstimateButton item info.
            /// </summary>
            [RepositoryItemInfo("f362dc7e-4a8f-4de5-b2b9-497185d51104")]
            public virtual RepoItemInfo CreateNewEstimateButtonInfo
            {
                get
                {
                    return _createnewestimatebuttonInfo;
                }
            }

            /// <summary>
            /// The OpenExistingEstimateButton item.
            /// </summary>
            [RepositoryItem("e0f87a37-a2f4-40b5-82e3-dc421eb4699c")]
            public virtual Ranorex.Button OpenExistingEstimateButton
            {
                get
                {
                    return _openexistingestimatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OpenExistingEstimateButton item info.
            /// </summary>
            [RepositoryItemInfo("e0f87a37-a2f4-40b5-82e3-dc421eb4699c")]
            public virtual RepoItemInfo OpenExistingEstimateButtonInfo
            {
                get
                {
                    return _openexistingestimatebuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}