///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The HBUserLogIn recording.
    /// </summary>
    [TestModule("39a778c6-72a6-4992-9789-b63c17daf0e6", ModuleType.Recording, 1)]
    public partial class HBUserLogIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static HBUserLogIn instance = new HBUserLogIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public HBUserLogIn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static HBUserLogIn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'UserLogin.UserNumberEntry'", repo.UserLogin.UserNumberEntryInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.UserLogin.UserNumberEntryInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserLogin.UserNumberEntry' at Center.", repo.UserLogin.UserNumberEntryInfo, new RecordItemIndex(1));
            repo.UserLogin.UserNumberEntry.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad3}' with focus on 'UserLogin.UserNumberEntry'.", repo.UserLogin.UserNumberEntryInfo, new RecordItemIndex(2));
            repo.UserLogin.UserNumberEntry.PressKeys("{NumPad1}{NumPad3}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'UserLogin.ButtonOK'", repo.UserLogin.ButtonOKInfo, new ActionTimeout(10000), new RecordItemIndex(3));
            repo.UserLogin.ButtonOKInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'UserLogin.ButtonOK' at Center.", repo.UserLogin.ButtonOKInfo, new RecordItemIndex(4));
            repo.UserLogin.ButtonOK.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
