///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateToSupportHCSS recording.
    /// </summary>
    [TestModule("407a39a3-ab47-4a2e-b84a-fb8867afa5c9", ModuleType.Recording, 1)]
    public partial class NavigateToSupportHCSS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static NavigateToSupportHCSS instance = new NavigateToSupportHCSS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateToSupportHCSS()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateToSupportHCSS Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // E.2
            Report.Log(ReportLevel.Info, "Mouse", "E.2\r\nMouse Left Click item 'HeavyBidRegistration.LinkRegistrationCode' at Center.", repo.HeavyBidRegistration.LinkRegistrationCodeInfo, new RecordItemIndex(0));
            repo.HeavyBidRegistration.LinkRegistrationCode.Click();
            Delay.Milliseconds(200);
            
            // E.2
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nE.2\r\nValidating AttributeRegEx (Text~'[support][hcss]') on item 'GoogleChrome.AddressBar'.", repo.GoogleChrome.AddressBarInfo, new RecordItemIndex(1));
                Validate.Attribute(repo.GoogleChrome.AddressBarInfo, "Text", new Regex("[support][hcss]"), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            // E.2
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nE.2\r\nValidating AttributeRegEx (Text~'[support][hcss]') on item 'GoogleChrome.Tabs'.", repo.GoogleChrome.TabsInfo, new RecordItemIndex(2));
                //Validate.Attribute(repo.GoogleChrome.TabsInfo, "Text", new Regex("[support][hcss]"), Validate.DefaultMessage, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // E.2
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nE.2\r\nWaiting 30s to exist. Associated repository item: 'GoogleChrome.TabSupportHCSS'", repo.GoogleChrome.TabSupportHCSSInfo, new ActionTimeout(30000), new RecordItemIndex(3));
                repo.GoogleChrome.TabSupportHCSSInfo.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // E.2
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nE.2\r\nWaiting 30s to exist. Associated repository item: 'GoogleChrome.LinkSupportHCSS'", repo.GoogleChrome.LinkSupportHCSSInfo, new ActionTimeout(30000), new RecordItemIndex(4));
                repo.GoogleChrome.LinkSupportHCSSInfo.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // E.2
            Report.Log(ReportLevel.Info, "Application", "E.2\r\nClosing application containing item 'GoogleChrome'.", repo.GoogleChrome.SelfInfo, new RecordItemIndex(5));
            Host.Current.CloseApplication(repo.GoogleChrome.Self, 10000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
