///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ReindexHeavyBidExternal recording.
    /// </summary>
    [TestModule("79760d42-1908-4bfb-a9ea-2af85fc59f6b", ModuleType.Recording, 1)]
    public partial class ReindexHeavyBidExternal : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ReindexHeavyBidExternal instance = new ReindexHeavyBidExternal();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ReindexHeavyBidExternal()
        {
            DefaultEstimates = "1-Bridge";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ReindexHeavyBidExternal Instance
        {
            get { return instance; }
        }

#region Variables

        string _DefaultEstimates;

        /// <summary>
        /// Gets or sets the value of variable DefaultEstimates.
        /// </summary>
        [TestVariable("284a411f-56a7-48ac-884e-7717debe5277")]
        public string DefaultEstimates
        {
            get { return _DefaultEstimates; }
            set { _DefaultEstimates = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\HeavyBidWS\\BIN\\REINDEX.EXE' with arguments ' HEAVYMULT' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\HeavyBidWS\\BIN\\REINDEX.EXE", " HEAVYMULT", "C:\\HeavyBidWS\\BIN\\", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReindexApplication.ButtonEllipisis' at Center.", repo.ReindexApplication.ButtonEllipisisInfo, new RecordItemIndex(1));
            repo.ReindexApplication.ButtonEllipisis.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ListExistingEstimates' at Center.", repo.HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ListExistingEstimatesInfo, new RecordItemIndex(2));
            repo.HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ListExistingEstimates.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$DefaultEstimates'.", new RecordItemIndex(3));
            Keyboard.Press(DefaultEstimates);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.GridViewOfEstimatesPopup.EstimateSearch.ButtonOk' at Center.", repo.HBPopupScreens.GridViewOfEstimatesPopup.EstimateSearch.ButtonOkInfo, new RecordItemIndex(4));
            repo.HBPopupScreens.GridViewOfEstimatesPopup.EstimateSearch.ButtonOk.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ButtonOk' at Center.", repo.HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ButtonOkInfo, new RecordItemIndex(5));
            repo.HBPopupScreens.GridViewOfEstimatesPopup.ListOfEstimatesPopup.ButtonOk.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'True' on item 'ReindexApplication.CurrentEstimateCheckbox'.", repo.ReindexApplication.CurrentEstimateCheckboxInfo, new RecordItemIndex(6));
            repo.ReindexApplication.CurrentEstimateCheckbox.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'True' on item 'ReindexApplication.SystemFilesCheckbox'.", repo.ReindexApplication.SystemFilesCheckboxInfo, new RecordItemIndex(7));
            repo.ReindexApplication.SystemFilesCheckbox.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReindexApplication.ButtonOK' at Center.", repo.ReindexApplication.ButtonOKInfo, new RecordItemIndex(8));
            repo.ReindexApplication.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReindexWarningScreen.ButtonOk' at Center.", repo.ReindexWarningScreen.ButtonOkInfo, new RecordItemIndex(9));
            repo.ReindexWarningScreen.ButtonOk.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
