///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RunSpreadsheetCalculations recording.
    /// </summary>
    [TestModule("8cfa06da-5018-46dd-8d9e-c93f72b24c17", ModuleType.Recording, 1)]
    public partial class RunSpreadsheetCalculations : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static RunSpreadsheetCalculations instance = new RunSpreadsheetCalculations();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RunSpreadsheetCalculations()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RunSpreadsheetCalculations Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.FileTab' at Center.", repo.HeavyBidApp.Tabs.FileTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.FileTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.File.ButtonOpenEstimate' at Center.", repo.HeavyBidApp.Buttons.File.ButtonOpenEstimateInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.File.ButtonOpenEstimate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBMultiDocumentInterface.Buttons.ButtonOK' at Center.", repo.HBMultiDocumentInterface.Buttons.ButtonOKInfo, new RecordItemIndex(2));
            repo.HBMultiDocumentInterface.Buttons.ButtonOK.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.HBMultiDocumentInterface.Buttons.ExpandAllTreeviewButton' at Center.", repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExpandAllTreeviewButtonInfo, new RecordItemIndex(3));
            repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.ExpandAllTreeviewButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.HBMultiDocumentInterface.TreeViewTree.FirstAvailableBiditem' at Center.", repo.HeavyBidApp.HBMultiDocumentInterface.TreeViewTree.FirstAvailableBiditemInfo, new RecordItemIndex(4));
            repo.HeavyBidApp.HBMultiDocumentInterface.TreeViewTree.FirstAvailableBiditem.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.HBMultiDocumentInterface.Buttons.SpreadsheetCalculationButton' at Center.", repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.SpreadsheetCalculationButtonInfo, new RecordItemIndex(5));
            repo.HeavyBidApp.HBMultiDocumentInterface.Buttons.SpreadsheetCalculationButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.FromFileButtons.OpenEstimateRelated.SelectSpreadsheet.FirstAvailableCalculations' at Center.", repo.HBPopupScreens.FromFileButtons.OpenEstimateRelated.SelectSpreadsheet.FirstAvailableCalculationsInfo, new RecordItemIndex(6));
            repo.HBPopupScreens.FromFileButtons.OpenEstimateRelated.SelectSpreadsheet.FirstAvailableCalculations.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBReportViewers.SpreadsheetCalculationViewer.CloseButton' at Center.", repo.HBReportViewers.SpreadsheetCalculationViewer.CloseButtonInfo, new RecordItemIndex(7));
            repo.HBReportViewers.SpreadsheetCalculationViewer.CloseButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
