///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SQLDriverReadme recording.
    /// </summary>
    [TestModule("da38b228-087f-49f0-8940-a004068cd583", ModuleType.Recording, 1)]
    public partial class SQLDriverReadme : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static SQLDriverReadme instance = new SQLDriverReadme();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SQLDriverReadme()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SQLDriverReadme Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\HeavyBid\\UTILITY' with arguments '' in normal mode.", new RecordItemIndex(0));
            //Host.Local.RunApplication("C:\\HeavyBid\\UTILITY", "", "", false);
            //Delay.Milliseconds(0);
            
            try {
                //Report.Log(ReportLevel.Info, "Application", "(Optional Action)\r\nRun application 'C:\\HeavyBid\\UTILITY\\SQL Drivers ReadMe.txt' with arguments '' in normal mode.", new RecordItemIndex(1));
                //Host.Local.RunApplication("C:\\HeavyBid\\UTILITY\\SQL Drivers ReadMe.txt", "", "", false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            CheckIfTXTFIleExists("C:\\HeavyBid\\UTILITY\\");
            Delay.Milliseconds(0);
            
            //CheckFilesExist("C:\\HeavyBid\\UTILITY\\", "SQL Drivers ReadMe.txt", ValueConverter.ArgumentFromString<int>("expectedCount", "1"), ValueConverter.ArgumentFromString<int>("timeout", "0"));
            //Delay.Milliseconds(0);
            
            //CheckFilesExist("C:\\HeavyJob\\Bin", ".tlx", ValueConverter.ArgumentFromString<int>("expectedCount", "6"), ValueConverter.ArgumentFromString<int>("timeout", "0"));
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
