///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestWhatsNewButton recording.
    /// </summary>
    [TestModule("00b958dc-dee3-423d-8fd7-6de0378cf8a8", ModuleType.Recording, 1)]
    public partial class TestWhatsNewButton : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static TestWhatsNewButton instance = new TestWhatsNewButton();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestWhatsNewButton()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestWhatsNewButton Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.WhatsNewTab' at Center.", repo.HeavyBidApp.Tabs.WhatsNewTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.WhatsNewTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.WhatsNew.NewHeavyBidFeaturesButton' at Center.", repo.HeavyBidApp.Buttons.WhatsNew.NewHeavyBidFeaturesButtonInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.WhatsNew.NewHeavyBidFeaturesButton.Click();
            Delay.Milliseconds(200);
            
            // E.6
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nE.6\r\nWaiting 30s to exist. Associated repository item: 'GoogleChrome.TabArticleHCSS'", repo.GoogleChrome.TabArticleHCSSInfo, new ActionTimeout(30000), new RecordItemIndex(2));
                repo.GoogleChrome.TabArticleHCSSInfo.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // E.6
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nE.6\r\nWaiting 30s to exist. Associated repository item: 'GoogleChrome.LinkHelpHCSS'", repo.GoogleChrome.LinkHelpHCSSInfo, new ActionTimeout(30000), new RecordItemIndex(3));
                repo.GoogleChrome.LinkHelpHCSSInfo.WaitForExists(30000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            // E.6
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nE.6\r\nValidating AttributeRegEx (AccessibleName~'[HCSS][Help]') on item 'GoogleChrome.Tabs'.", repo.GoogleChrome.TabsInfo, new RecordItemIndex(4));
                Validate.Attribute(repo.GoogleChrome.TabsInfo, "AccessibleName", new Regex("[HCSS][Help]"), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            // E.6
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nE.6\r\nValidating AttributeRegEx (Text~'[help][hcss][release]') on item 'GoogleChrome.AddressBar'.", repo.GoogleChrome.AddressBarInfo, new RecordItemIndex(5));
                Validate.Attribute(repo.GoogleChrome.AddressBarInfo, "Text", new Regex("[help][hcss][release]"), Validate.DefaultMessage, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'GoogleChrome.LinkHelpHCSS'.", repo.GoogleChrome.LinkHelpHCSSInfo, new RecordItemIndex(6));
            Host.Current.CloseApplication(repo.GoogleChrome.LinkHelpHCSS, 1000);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
