///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TestWrongRegCode recording.
    /// </summary>
    [TestModule("78ae137a-02fe-4c28-ba10-108bf3ab76d5", ModuleType.Recording, 1)]
    public partial class TestWrongRegCode : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static TestWrongRegCode instance = new TestWrongRegCode();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TestWrongRegCode()
        {
            RegistrationCode = "28d7c9f7-0f26-4b09-8b40-16c84e43681b";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TestWrongRegCode Instance
        {
            get { return instance; }
        }

#region Variables

        string _RegistrationCode;

        /// <summary>
        /// Gets or sets the value of variable RegistrationCode.
        /// </summary>
        [TestVariable("7371ef27-f2d3-4321-bda2-e53ddec4900b")]
        public string RegistrationCode
        {
            get { return _RegistrationCode; }
            set { _RegistrationCode = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidRegistration.RegistrationEntry' at Center.", repo.HeavyBidRegistration.RegistrationEntryInfo, new RecordItemIndex(0));
            //repo.HeavyBidRegistration.RegistrationEntry.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(1));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$RegistrationCode' with focus on 'HeavyBidRegistration.RegistrationEntry'.", repo.HeavyBidRegistration.RegistrationEntryInfo, new RecordItemIndex(2));
            repo.HeavyBidRegistration.RegistrationEntry.PressKeys(RegistrationCode);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidRegistration.Check' at Center.", repo.HeavyBidRegistration.CheckInfo, new RecordItemIndex(3));
            repo.HeavyBidRegistration.Check.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Text~'attempting') on item 'HeavyBidRegistration.WrongRegistrationCodeTextbox'.", repo.HeavyBidRegistration.WrongRegistrationCodeTextboxInfo, new RecordItemIndex(4));
            Validate.AttributeRegex(repo.HeavyBidRegistration.WrongRegistrationCodeTextboxInfo, "Text", new Regex("attempting"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidRegistration.Submit' at Center.", repo.HeavyBidRegistration.SubmitInfo, new RecordItemIndex(5));
            repo.HeavyBidRegistration.Submit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ActivateHeavyBidServer.ButtonOK'", repo.ActivateHeavyBidServer.ButtonOKInfo, new ActionTimeout(10000), new RecordItemIndex(6));
            repo.ActivateHeavyBidServer.ButtonOKInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeRegex (Text~'attempting') on item 'HeavyBidRegistration.WrongRegistrationCodePopupTextbox'.", repo.HeavyBidRegistration.WrongRegistrationCodePopupTextboxInfo, new RecordItemIndex(7));
            Validate.AttributeRegex(repo.HeavyBidRegistration.WrongRegistrationCodePopupTextboxInfo, "Text", new Regex("attempting"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ActivateHeavyBidServer.ButtonOK' at Center.", repo.ActivateHeavyBidServer.ButtonOKInfo, new RecordItemIndex(8));
            repo.ActivateHeavyBidServer.ButtonOK.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
