///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The UninstallCrystal recording.
    /// </summary>
    [TestModule("ae8f2f05-5ac9-49af-81aa-e73092f6bb8d", ModuleType.Recording, 1)]
    public partial class UninstallCrystal : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static UninstallCrystal instance = new UninstallCrystal();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public UninstallCrystal()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static UninstallCrystal Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ProgramsAndFeatures.Row0.HCSSCrystalXIIntegration'", repo.ProgramsAndFeatures.Row0.HCSSCrystalXIIntegrationInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.ProgramsAndFeatures.Row0.HCSSCrystalXIIntegrationInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProgramsAndFeatures.Row0.HCSSCrystalXIIntegration' at Center.", repo.ProgramsAndFeatures.Row0.HCSSCrystalXIIntegrationInfo, new RecordItemIndex(1));
            repo.ProgramsAndFeatures.Row0.HCSSCrystalXIIntegration.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ProgramsAndFeatures.ButtonUninstall'", repo.ProgramsAndFeatures.ButtonUninstallInfo, new ActionTimeout(10000), new RecordItemIndex(2));
            repo.ProgramsAndFeatures.ButtonUninstallInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProgramsAndFeatures.ButtonUninstall' at Center.", repo.ProgramsAndFeatures.ButtonUninstallInfo, new RecordItemIndex(3));
            repo.ProgramsAndFeatures.ButtonUninstall.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'ProgramsAndFeatures.ButtonYes'", repo.ProgramsAndFeatures.ButtonYesInfo, new ActionTimeout(10000), new RecordItemIndex(4));
            repo.ProgramsAndFeatures.ButtonYesInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProgramsAndFeatures.ButtonYes' at Center.", repo.ProgramsAndFeatures.ButtonYesInfo, new RecordItemIndex(5));
            repo.ProgramsAndFeatures.ButtonYes.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
