///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateHBHelpScreen recording.
    /// </summary>
    [TestModule("4fd71e3b-908c-4d93-9811-290c25bd053f", ModuleType.Recording, 1)]
    public partial class ValidateHBHelpScreen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ValidateHBHelpScreen instance = new ValidateHBHelpScreen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateHBHelpScreen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateHBHelpScreen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApplication.Help' at 30;16.", repo.HeavyBidApplication.HelpInfo, new RecordItemIndex(0));
            repo.HeavyBidApplication.Help.Click("30;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HEAVYBID.AboutHeavyBid' at 90;12.", repo.HEAVYBID.AboutHeavyBidInfo, new RecordItemIndex(1));
            repo.HEAVYBID.AboutHeavyBid.Click("90;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidServerSetup.SystemInfo' at 73;6.", repo.HeavyBidServerSetup.SystemInfoInfo, new RecordItemIndex(2));
            repo.HeavyBidServerSetup.SystemInfo.Click("73;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WelcomeToHeavyBidScreen.OpenExistingEstimateButton' at 74;18.", repo.WelcomeToHeavyBidScreen.OpenExistingEstimateButtonInfo, new RecordItemIndex(3));
            repo.WelcomeToHeavyBidScreen.OpenExistingEstimateButton.Click("74;18");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
