///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateHBLaunch recording.
    /// </summary>
    [TestModule("e46c80a6-d7fa-4a4d-817c-02019abb12b8", ModuleType.Recording, 1)]
    public partial class ValidateHBLaunch : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ValidateHBLaunch instance = new ValidateHBLaunch();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateHBLaunch()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateHBLaunch Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeToHeavyBidScreen.WelcomeToHeavyBid20181'.", repo.WelcomeToHeavyBidScreen.WelcomeToHeavyBid20181Info, new RecordItemIndex(0));
            Validate.Exists(repo.WelcomeToHeavyBidScreen.WelcomeToHeavyBid20181Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeToHeavyBidScreen.OpenEstimateButton'.", repo.WelcomeToHeavyBidScreen.OpenEstimateButtonInfo, new RecordItemIndex(1));
            Validate.Exists(repo.WelcomeToHeavyBidScreen.OpenEstimateButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeToHeavyBidScreen.CreateNewEstimateButton'.", repo.WelcomeToHeavyBidScreen.CreateNewEstimateButtonInfo, new RecordItemIndex(2));
            Validate.Exists(repo.WelcomeToHeavyBidScreen.CreateNewEstimateButtonInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WelcomeToHeavyBidScreen.OpenExistingEstimateButton'.", repo.WelcomeToHeavyBidScreen.OpenExistingEstimateButtonInfo, new RecordItemIndex(3));
            Validate.Exists(repo.WelcomeToHeavyBidScreen.OpenExistingEstimateButtonInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
