///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HB_INSTALL_AUTO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateHBAboutHB recording.
    /// </summary>
    [TestModule("4fd71e3b-908c-4d93-9811-290c25bd053f", ModuleType.Recording, 1)]
    public partial class ValidateHBAboutHB : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HB_INSTALL_AUTORepository repository.
        /// </summary>
        public static HB_INSTALL_AUTORepository repo = HB_INSTALL_AUTORepository.Instance;

        static ValidateHBAboutHB instance = new ValidateHBAboutHB();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateHBAboutHB()
        {
            YearVersion = "2018.1";
            RegistrationName = "Test Company 999";
            SystemType = "Advanced";
            Licenses = "100";
            InstallType = "Multiuser";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateHBAboutHB Instance
        {
            get { return instance; }
        }

#region Variables

        string _RegistrationName;

        /// <summary>
        /// Gets or sets the value of variable RegistrationName.
        /// </summary>
        [TestVariable("fd9a158d-db82-43f9-adef-d7560b4aefd9")]
        public string RegistrationName
        {
            get { return _RegistrationName; }
            set { _RegistrationName = value; }
        }

        string _SystemType;

        /// <summary>
        /// Gets or sets the value of variable SystemType.
        /// </summary>
        [TestVariable("baf4656d-c96b-4cd0-b790-ecf29039a99c")]
        public string SystemType
        {
            get { return _SystemType; }
            set { _SystemType = value; }
        }

        string _Licenses;

        /// <summary>
        /// Gets or sets the value of variable Licenses.
        /// </summary>
        [TestVariable("89cc8f80-fe26-4a5d-84e5-cfb65d07b8af")]
        public string Licenses
        {
            get { return _Licenses; }
            set { _Licenses = value; }
        }

        string _InstallType;

        /// <summary>
        /// Gets or sets the value of variable InstallType.
        /// </summary>
        [TestVariable("3b4745cb-9a75-48e2-9335-37686931ea58")]
        public string InstallType
        {
            get { return _InstallType; }
            set { _InstallType = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable YearVersion.
        /// </summary>
        [TestVariable("5cd460da-091f-49fb-b058-491c186c0db3")]
        public string YearVersion
        {
            get { return repo.YearVersion; }
            set { repo.YearVersion = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Tabs.HelpTab' at Center.", repo.HeavyBidApp.Tabs.HelpTabInfo, new RecordItemIndex(0));
            repo.HeavyBidApp.Tabs.HelpTab.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidApp.Buttons.Help.HelpAboutHeavyBidButton' at Center.", repo.HeavyBidApp.Buttons.Help.HelpAboutHeavyBidButtonInfo, new RecordItemIndex(1));
            repo.HeavyBidApp.Buttons.Help.HelpAboutHeavyBidButton.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~$YearVersion) on item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLine'.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLineInfo, new RecordItemIndex(2));
                Validate.AttributeRegex(repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLineInfo, "Text", new Regex(YearVersion), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~$RegistrationName) on item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.CompanyNameTextLine'.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.CompanyNameTextLineInfo, new RecordItemIndex(3));
                Validate.AttributeRegex(repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.CompanyNameTextLineInfo, "Text", new Regex(RegistrationName), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~$SystemType) on item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLine'.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLineInfo, new RecordItemIndex(4));
                Validate.AttributeRegex(repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.HBTextLineInfo, "Text", new Regex(SystemType), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~$InstallType) on item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLine'.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLineInfo, new RecordItemIndex(5));
                Validate.AttributeRegex(repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLineInfo, "Text", new Regex(InstallType), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeRegex (Text~$Licenses) on item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLine'.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLineInfo, new RecordItemIndex(6));
                Validate.AttributeRegex(repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.LicenseAmountTextLineInfo, "Text", new Regex(Licenses), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.SystemInfo' at Center.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.SystemInfoInfo, new RecordItemIndex(7));
            repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.SystemInfo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.FromHelpButtons.SystemInformationAboutHB.CloseButton' at Center.", repo.HBPopupScreens.FromHelpButtons.SystemInformationAboutHB.CloseButtonInfo, new RecordItemIndex(8));
            repo.HBPopupScreens.FromHelpButtons.SystemInformationAboutHB.CloseButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HBPopupScreens.FromHelpButtons.AboutHeavyBid.CloseButton' at Center.", repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.CloseButtonInfo, new RecordItemIndex(9));
            repo.HBPopupScreens.FromHelpButtons.AboutHeavyBid.CloseButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
